
services:

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  mongodb:
    image: docker.io/bitnami/mongodb:7.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    
    ports:
      - '27017:27017'

  
volumes:
  mongodb_master_data:
    driver: local